config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :people
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'sessions/welcome'
  resources :newusers
  get 'book/add'
  get 'book/delete'
  get 'book/destroy'
  get 'book/edit'
  get 'book/update'
  get 'book/search'
  get 'book/save'
  get 'book/list'
  get 'book/show'
  get 'book/create'
  get 'book/new'
  get 'book/dummy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get 'second/index'
 # get 'second/hello'
  get 'user/create'
  get 'user/register'
  get 'user/login'
  get 'first/welcome'
  get 'first/login'
  root 'first#welcome'
  get "/first",to:"first#welcome"
  get 'display/hello'
  match ':controller(/:action(/:id(.:format)))',:via =>[:get,:post]

  #get 'home/index'
  #root 'home#index'
  #resources :users
  #resources:employees
  #resources :sessions, only: [:new, :create, :destroy]
  #get 'login', to: 'sessions#new', as: 'login'
  #get 'logout', to: 'sessions#destroy', as: 'logout'
  #get 'welcome', to: 'sessions#welcome', as: 'welcome'

#get 'display/register'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/custacc.rb
class Custacc < ApplicationRecord
	belongs_to:customer
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_one:custacc
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_secure_password
 validates :email, presence: true, uniqueness: true

end

app/models/info.rb
class Info < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/newuser.rb
class Newuser < ApplicationRecord
 has_secure_password
 #validates :email, presence: true
 validates :email, presence: true, uniqueness: true
end 

app/models/person.rb
class Person < ApplicationRecord
  has_secure_password
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def add
    #@book=Book.new
  end
  def edit
    @book=Book.find(params[:id])
  end
  def delete
    #which record delete
    @book=Book.find(params[:id])
  end
  def destroy
    bk=Book.find(params[:id])
    bk.destroy
    redirect_to(action:'list')
  end
  def update
    @book=Book.find(params[:id])
    id=@book.id
    if @book.update_attributes(book_params)
      redirect_to(action: 'list')
    else
      render('edit')
    end
  end

  def new
    #@book=Book.new(book_params)
    @book=Book.new
  end
  def create
    @book=Book.new(book_params)
    if @book.save
      redirect_to(action:'dummy')
     # redirect_to(action:'list')
    else
      flash[:notice]="Error:record not created"
      render(action:'new')
    end
  end

  def search
  end

  def save
  end

  def list
    #fetching data from db
    @books=Book.all
  end
  def new
    #@book=Book.new
  end
  def show
    @book=Book.find(params[:id])
  end
  def book_params
    params.require(:books).permit(:name,:author,:price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newusers_helper.rb
module NewusersHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/demo/index.html.erb
<% if current_user %>
 Logged in as <%= current_user.email %>.
 <%= link_to 'Log Out', logout_path %>
<% else %>
 <%= link_to 'Sign Up', signup_path %> or
 <%= link_to 'Log In', login_path %>
<% end %>
<p id='notice'><%= notice %></p>
<h1>Home Page</h1>


app/views/demo/login.html.erb

<div class ="Register page">
   <h2> Login</h2>
   <%=form_for(:users,url: {controller:"user", action:'create'})do |t|%>
    <table summary="Book form fields">
    	
    	<tr>
    		<th> Email </th>
    		<td> <%=t.text_field(:email)%> </td>
    	</tr>
    	<tr>
    		<th> Password </th>
    		<td> <%=t.text_field(:password)%> </td>
    	</tr>
    </table>
    <div class="form-button">
    	<%=submit_tag("Login")%>
    </div>
    <%end %>
</div>


app/views/demo/register.html.erb

<div class ="Register page">
   <h2> Register</h2>
   <%=form_for(:users,url: {controller:"user", action:'create'})do |t|%>
    <table summary="Book form fields">
    	<tr>
    		<th> Username </th>
    		<td> <%=t.text_field(:username)%> </td>
    	</tr>
    	<tr>
    		<th> Email </th>
    		<td> <%=t.text_field(:email)%> </td>
    	</tr>
    	<tr>
    		<th> Password </th>
    		<td> <%=t.text_field(:password)%> </td>
    	</tr>
    </table>
    <div class="form-button">
    	<%=submit_tag("Register")%>
    </div>
    <%end %>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>