config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :people
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'sessions/welcome'
  resources :newusers
  get 'book/add'
  get 'book/delete'
  get 'book/destroy'
  get 'book/edit'
  get 'book/update'
  get 'book/search'
  get 'book/save'
  get 'book/list'
  get 'book/show'
  get 'book/create'
  get 'book/new'
  get 'book/dummy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get 'second/index'
 # get 'second/hello'
  get 'user/create'
  get 'user/register'
  get 'user/login'
  get 'first/welcome'
  get 'first/login'
  root 'first#welcome'
  get "/first",to:"first#welcome"
  get 'display/hello'
  match ':controller(/:action(/:id(.:format)))',:via =>[:get,:post]

  #get 'home/index'
  #root 'home#index'
  #resources :users
  #resources:employees
  #resources :sessions, only: [:new, :create, :destroy]
  #get 'login', to: 'sessions#new', as: 'login'
  #get 'logout', to: 'sessions#destroy', as: 'logout'
  #get 'welcome', to: 'sessions#welcome', as: 'welcome'

#get 'display/register'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/custacc.rb
class Custacc < ApplicationRecord
	belongs_to:customer
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_one:custacc
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_secure_password
 validates :email, presence: true, uniqueness: true

end

app/models/info.rb
class Info < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/newuser.rb
class Newuser < ApplicationRecord
 has_secure_password
 #validates :email, presence: true
 validates :email, presence: true, uniqueness: true
end 

app/models/person.rb
class Person < ApplicationRecord
  has_secure_password
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def add
    #@book=Book.new
  end
  def edit
    @book=Book.find(params[:id])
  end
  def delete
    #which record delete
    @book=Book.find(params[:id])
  end
  def destroy
    bk=Book.find(params[:id])
    bk.destroy
    redirect_to(action:'list')
  end
  def update
    @book=Book.find(params[:id])
    id=@book.id
    if @book.update_attributes(book_params)
      redirect_to(action: 'list')
    else
      render('edit')
    end
  end

  def new
    #@book=Book.new(book_params)
    @book=Book.new
  end
  def create
    @book=Book.new(book_params)
    if @book.save
      redirect_to(action:'dummy')
     # redirect_to(action:'list')
    else
      flash[:notice]="Error:record not created"
      render(action:'new')
    end
  end

  def search
  end

  def save
  end

  def list
    #fetching data from db
    @books=Book.all
  end
  def new
    #@book=Book.new
  end
  def show
    @book=Book.find(params[:id])
  end
  def book_params
    params.require(:books).permit(:name,:author,:price)
  end
end

app/controllers/first_controller.rb
class FirstController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/newuser_controller.rb
class NewuserController < ApplicationController
  before_action :set_newuser, only: [:show, :edit, :update, :destroy]

  # GET /newusers
  # GET /newusers.json
  def index
    @newusers = Newuser.all
  end

  # GET /newusers/1
  # GET /newusers/1.json
  def show
  end

  # GET /newusers/new
  def new
    @newuser = Newuser.new
  end

  # GET /newusers/1/edit
  def edit
  end

  # POST /newusers
  # POST /newusers.json
  def create
    @newuser = Newuser.new(newuser_params)

    respond_to do |format|
      if @newuser.save
        format.html { redirect_to @newuser, notice: 'Newuser was successfully created.' }
        format.json { render :show, status: :created, location: @newuser }
      else
        format.html { render :new }
        format.json { render json: @newuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newusers/1
  # PATCH/PUT /newusers/1.json
  def update
    respond_to do |format|
      if @newuser.update(newuser_params)
        format.html { redirect_to @newuser, notice: 'Newuser was successfully updated.' }
        format.json { render :show, status: :ok, location: @newuser }
      else
        format.html { render :edit }
        format.json { render json: @newuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newusers/1
  # DELETE /newusers/1.json
  def destroy
    @newuser.destroy
    respond_to do |format|
      format.html { redirect_to newusers_url, notice: 'Newuser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newuser
      @newuser = Newuser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newuser_params
      params.require(:newuser).permit(:name, :mobile, :email, :password, :password_confirmation, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newusers_helper.rb
module NewusersHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/newusers/_form.html.erb
<%= form_with(model: newuser, local: true) do |form| %>
  <% if newuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newuser.errors.count, "error") %> prohibited this newuser from being saved:</h2>

      <ul>
        <% newuser.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/newusers/edit.html.erb
<h1>Editing Newuser</h1>

<%= render 'form', newuser: @newuser %>

<%= link_to 'Show', @newuser %> |
<%= link_to 'Back', newusers_path %>

app/views/newusers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Newusers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newusers.each do |newuser| %>
      <tr>
        <td><%= newuser.name %></td>
        <td><%= newuser.mobile %></td>
        <td><%= newuser.email %></td>
        <td><%= newuser.address %></td>
        <td><%= link_to 'Show', newuser %></td>
        <td><%= link_to 'Edit', edit_newuser_path(newuser) %></td>
        <td><%= link_to 'Destroy', newuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newuser', new_newuser_path %>

app/views/newusers/new.html.erb
<h1>New Newuser</h1>

<%= render 'form', newuser: @newuser %>


<%= link_to "Back ", controller: "Newuser", action: 'index', class: "back-link"  %>

app/views/newusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @newuser.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @newuser.mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @newuser.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @newuser.address %>
</p>

<%= link_to 'Edit', edit_newuser_path(@newuser) %> |
<%= link_to 'Back', newusers_path %>